export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  HOME: '/',
  DASHBOARD: '/dashboard',
  MY_TASKS: '/my-tasks',
  PROJECTS: '/projects',
  project: (id: number | string, tab = 'overview') => `/projects/${id}/${tab}`,
  SPRINTS: '/sprints',
  BOARD: '/board',
  task: (idOrKey: number | string) => `/tasks/${idOrKey}`,
  USERS: '/users',
  ROLES: '/roles',
  TEAMS: '/teams',
  BRANCHES: '/branches',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_SETTINGS: '/notifications/settings',
  AUDIT_LOG: '/audit-log',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  FORBIDDEN: '/403',
} as const;
