import { theme, type ThemeConfig } from 'antd';

/** Linear-inspired dark theme. Colors mirror styles/variables.css. */
export const appTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: '#5e6ad2',
    colorInfo: '#5e6ad2',
    colorSuccess: '#4cb782',
    colorWarning: '#f2994a',
    colorError: '#eb5757',
    colorBgBase: '#0f0f10',
    colorBgLayout: '#090909',
    colorBgContainer: '#151517',
    colorBgElevated: '#1c1c1f',
    colorBorder: '#2a2a2f',
    colorBorderSecondary: '#232326',
    colorText: '#ededef',
    colorTextSecondary: '#9c9ca3',
    colorTextTertiary: '#66666d',
    colorTextQuaternary: '#4a4a50',
    colorFillTertiary: 'rgba(255,255,255,0.04)',
    colorFillSecondary: 'rgba(255,255,255,0.06)',
    colorLink: '#8b93e6',
    colorLinkHover: '#a9afee',
    fontFamily: "'Inter', -apple-system, 'Segoe UI', Roboto, sans-serif",
    fontSize: 13,
    borderRadius: 6,
    borderRadiusLG: 10,
    controlHeight: 32,
    controlHeightSM: 26,
    boxShadowSecondary: '0 8px 30px rgba(0,0,0,0.5)',
    motionDurationMid: '0.15s',
  },
  components: {
    Table: {
      headerBg: 'transparent',
      headerSplitColor: 'transparent',
      rowHoverBg: '#1c1c1f',
      borderColor: '#232326',
      colorBgContainer: 'transparent',
      cellPaddingBlockSM: 7,
    },
    Modal: { contentBg: '#151517', headerBg: '#151517', footerBg: '#151517' },
    Drawer: { colorBgElevated: '#111113' },
    Tabs: { itemColor: '#9c9ca3', itemSelectedColor: '#ededef', inkBarColor: '#ededef', itemHoverColor: '#ededef', horizontalMargin: '0' },
    Button: { primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none', defaultBg: '#1c1c1f', defaultBorderColor: '#2a2a2f' },
    Select: { optionSelectedBg: '#232327', optionActiveBg: '#1c1c1f' },
    Menu: { itemBg: 'transparent', darkItemBg: 'transparent' },
    Tag: { defaultBg: '#1c1c1f' },
    Collapse: { headerBg: '#151517', contentBg: 'transparent' },
    Segmented: { itemSelectedBg: '#2a2a2f', trackBg: '#151517' },
    Card: { colorBgContainer: '#151517' },
  },
};
