import { theme, type ThemeConfig } from 'antd';

import type { ThemeMode } from '@/shared/lib/theme';

/** Linear-inspired palettes. Colors mirror styles/variables.css. */
const PRIMARY = '#165dff';

const PALETTE = {
  dark: {
    success: '#4cb782',
    warning: '#f2994a',
    error: '#eb5757',
    bgBase: '#0f0f10',
    bgLayout: '#090909',
    bgContainer: '#151517',
    bgElevated: '#1c1c1f',
    drawerBg: '#111113',
    border: '#2a2a2f',
    borderSecondary: '#232326',
    text: '#ededef',
    textSecondary: '#9c9ca3',
    textTertiary: '#66666d',
    textQuaternary: '#4a4a50',
    fillTertiary: 'rgba(255,255,255,0.04)',
    fillSecondary: 'rgba(255,255,255,0.06)',
    link: '#4080ff',
    linkHover: '#6aa1ff',
    shadow: '0 8px 30px rgba(0,0,0,0.5)',
    hover: '#1c1c1f',
    selected: '#232327',
    segmentSelected: '#2a2a2f',
  },
  light: {
    success: '#2f9e6a',
    warning: '#e5832f',
    error: '#e5484d',
    bgBase: '#ffffff',
    bgLayout: '#f3f3f5',
    bgContainer: '#ffffff',
    bgElevated: '#ffffff',
    drawerBg: '#ffffff',
    border: '#dcdce2',
    borderSecondary: '#e6e6eb',
    text: '#1b1b1f',
    textSecondary: '#5f5f68',
    textTertiary: '#8f8f98',
    textQuaternary: '#b4b4bc',
    fillTertiary: 'rgba(16,16,24,0.035)',
    fillSecondary: 'rgba(16,16,24,0.06)',
    link: '#165dff',
    linkHover: '#4080ff',
    shadow: '0 8px 30px rgba(16,16,24,0.12)',
    hover: '#f4f4f6',
    selected: '#ececf1',
    segmentSelected: '#ffffff',
  },
} as const;

export const getAppTheme = (mode: ThemeMode): ThemeConfig => {
  const p = PALETTE[mode];
  return {
    algorithm: mode === 'dark' ? theme.darkAlgorithm : theme.defaultAlgorithm,
    token: {
      colorPrimary: PRIMARY,
      colorInfo: PRIMARY,
      colorSuccess: p.success,
      colorWarning: p.warning,
      colorError: p.error,
      colorBgBase: p.bgBase,
      colorBgLayout: p.bgLayout,
      colorBgContainer: p.bgContainer,
      colorBgElevated: p.bgElevated,
      colorBorder: p.border,
      colorBorderSecondary: p.borderSecondary,
      colorText: p.text,
      colorTextSecondary: p.textSecondary,
      colorTextTertiary: p.textTertiary,
      colorTextQuaternary: p.textQuaternary,
      colorFillTertiary: p.fillTertiary,
      colorFillSecondary: p.fillSecondary,
      colorLink: p.link,
      colorLinkHover: p.linkHover,
      fontFamily: "'Inter', -apple-system, 'Segoe UI', Roboto, sans-serif",
      fontSize: 13,
      borderRadius: 6,
      borderRadiusLG: 12,
      controlHeight: 32,
      controlHeightSM: 26,
      boxShadowSecondary: p.shadow,
      motionDurationMid: '0.15s',
    },
    components: {
      Table: {
        headerBg: 'transparent',
        headerSplitColor: 'transparent',
        rowHoverBg: p.hover,
        borderColor: p.borderSecondary,
        colorBgContainer: 'transparent',
        cellPaddingBlockSM: 7,
      },
      Modal: { contentBg: p.bgContainer, headerBg: p.bgContainer, footerBg: p.bgContainer },
      Drawer: { colorBgElevated: p.drawerBg },
      Tabs: { itemColor: p.textSecondary, itemSelectedColor: p.text, inkBarColor: p.text, itemHoverColor: p.text, horizontalMargin: '0' },
      Button: {
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        defaultBg: p.bgElevated,
        defaultBorderColor: p.border,
        controlHeight: 34,
        paddingInline: 16,
        borderRadius: 8,
        fontWeight: 500,
      },
      Select: { optionSelectedBg: p.selected, optionActiveBg: p.hover },
      Menu: { itemBg: 'transparent', darkItemBg: 'transparent' },
      Tag: { defaultBg: p.hover },
      Collapse: { headerBg: p.bgContainer, contentBg: 'transparent' },
      Segmented: { itemSelectedBg: p.segmentSelected, trackBg: mode === 'dark' ? p.bgContainer : p.selected },
      Card: { colorBgContainer: p.bgContainer },
    },
  };
};
